-- local tinymist = vim.env.TINYMIST_PATH
-- local websocat = vim.env.WEBSOCAT_PATH
-- require("typst-preview").setup({
-- 	dependencies_bin = {
-- 		["tinymist"] = tinymist, --NOTE: Relies on env var, want to move to category definition at some point if I can figure out how to mix explicit and implicit category stuffs.
-- 		["websocat"] = websocat,
-- 	},
-- })
